jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '8'

      - name: Build site
        working-directory: poker
        run: mvn clean site

      - name: Copy Javadoc to docs/
        run: |
          rm -rf docs
          mkdir docs
          cp -R poker/target/site/apidocs/* docs/

      - name: Commit docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --quiet --cached || git commit -m "📚 Update Javadoc"
          git push
